vim.keymap.set('n', 'zn', '<cmd>cnext<CR>zz')
vim.keymap.set('n', 'zp', '<cmd>cprev<CR>zz')
vim.keymap.set('n', '<leader>ln', '<cmd>lnext<CR>zz')
vim.keymap.set('n', '<leader>lp', '<cmd>lprev<CR>zz')
vim.keymap.set('n', '<leader>te', vim.cmd.Telescope)
vim.keymap.set('n', '<leader>cb', ':!cargo build<CR>')
vim.keymap.set('n', '<leader>cf', ':!cargo fmt --all<CR>')
vim.keymap.set('n', '<leader>tg', ':Termdebug /home/hatim/git-repos/re/target/debug/re<CR>')
vim.keymap.set('n', '<leader>gg', vim.cmd.Git)
vim.keymap.set('n', '<leader>ww', vim.cmd.w)
